"""empty message

Revision ID: 4d9211543b1b
Revises: aa4eb93fe0cf
Create Date: 2021-10-13 00:32:41.037821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d9211543b1b'
down_revision = 'aa4eb93fe0cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('register_phonebook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=True),
    sa.Column('last_name', sa.String(length=150), nullable=True),
    sa.Column('phone_number', sa.String(length=150), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('post', sa.Column('date_created', sa.DateTime(), nullable=False))
    op.drop_column('post', 'date_create')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('date_create', sa.DATETIME(), nullable=False))
    op.drop_column('post', 'date_created')
    op.drop_table('register_phonebook')
    # ### end Alembic commands ###
